/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package compile.plugin.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        SamplePlugin classUnderTest = new SamplePlugin();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
